let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Wings",
    price: 45,
    desc: "Organic, Fresh, Low-fat, From New zealand.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Chips",
    price: 15,
    desc: "Low-fat, Low-sodium, Low-oil",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Tuffle",
    price: 25,
    desc: "Fresh, Give you a didferent taste of everthing.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Egg",
    price: 30,
    desc: "Organic, Low-presure Farming.",
    img: "images/img-4.jpg",
  },
  {
    id: "123fhcbcv",
    name: "Wine",
    price: 200,
    desc: "Since 1998, Good for fine dining.",
    img: "images/img-5.jpg",
  },
  {
    id: "54465815",
    name: "Rice",
    price: 49.9,
    desc: "Form Thailand, It is Creamy and Fragrance.",
    img: "images/img-6.jpg",
  },
  {
    id: "87896534",
    name: "Sake",
    price: 100,
    desc: "Best Seller, Import from Japan.",
    img: "images/img-7.jpg",
  },
  {
    id: "56461268",
    name: "Olive Oil",
    price: 39.9,
    desc: "Rich olive Fragrance, Better cook with anything.",
    img: "images/img-8.jpg",
  },
];
